server:
  port: 3344
spring:
  application:
    #注册进Eureka服务器的微服务名
    name:  cloud-config-center
  cloud:
    config:
      server:
        git:
          #GitHub上面的git仓库名字
          uri: https://github.com/nrvcer/springcloud-config.git
          username: nrvcer
          ####搜索目录
          search-paths:
            - springcloud-config
          password: Wzh147258369
          skip-ssl-validation: true
      ####读取分支
      label: main
  #rabbitmq相关配置
  rabbitmq:
    host: 124.222.104.217
    port: 5672
    username: root
    password: root
    virtual-host: /
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'